### ISSUE TITLE
Incorrect docstring on `matcher`

### ISSUE THREAD

**Issue by SevereOverfl0w** [prepor/twarc#10]
Matcher's docstring claims that `{:everything true}` is the syntax for an everything matcher, but this seems not to be the case.  Instead the syntax is `:everything`:

```
user=> (require '[twarc.core :as twarc])
nil
user=> (twarc/matcher {:everything true} :job)
nil
user=> (twarc/matcher :everything :job)
#object[org.quartz.impl.matchers.EverythingMatcher 0x5b7ff8cf "org.quartz.impl.matchers.EverythingMatcher@bb034737"]
```

May I suggest that the fix leaves the old behavior in order for anyone who has worked around it to have their code continue to work?

**Comment by prepor** [comment]
thank you for reporting @SevereOverfl0w 

I think it's just enough to fix docstring to match actual behavior.
