### ISSUE TITLE
Stateful jobs don't persist changes in state

### ISSUE THREAD

**Issue by RokLenarcic** [prepor/twarc#16]
If I upgrade from `0.1.10` to `0.1.12` or later, stateful jobs that are backed by a database stop working.

This is caused by this change:
https://github.com/prepor/twarc/pull/7/files#diff-a72d3f0df7c6d43e920442fdc42b450aR25

After that change you are updating the merged map here:
https://github.com/prepor/twarc/pull/7/files#diff-a72d3f0df7c6d43e920442fdc42b450aR29

Updating the merged map does nothing to the original JobDataMap so any changes are not persisted at all.

You can reproduce this by running the stateful job example from the readme, the counter will not increase at all.

The solution is to change line at https://github.com/prepor/twarc/blob/master/java/twarc/TwarcStatefullJob.java#L29

To `context.getJobDetail().getJobDataMap().put("state", result);`

**Comment by prepor** [comment]
Thank you for the bug report! Fix in 0.1.15. Such cases definitely should be covered by tests...
